che-incubator/che-workspace-telemetry-client

.github/workflows/nodejs-publish.yaml

Correct the publish workflow file

---

.github/workflows/nodejs-publish.yaml

Set java version correctly

---

.github/workflows/nodejs-publish.yaml

still no tests yet

---

.github/workflows/nodejs-publish.yaml

Set npm registry

---

.github/workflows/nodejs-publish.yaml

set project-specific npmrc and publish

---

.github/workflows/nodejs-publish.yaml

Try yarn publish

---

.github/workflows/backend-base-publish.yaml
backend-base/pom.xml

Publish the backend-base client to the github maven repo

Publish master to github

---

.github/workflows/backend-base-publish.yaml

Rename publish job

---

.github/workflows/backend-base-publish.yaml

Need .m2 directory

---

pom.xml

Update parent dependency on 1.0.0

---

.github/workflows/backend-base-publish.yaml
backend-base/pom.xml

deploy to che-incubator

---

backend-base/pom.xml
javascript/pom.xml
pom.xml

Try snapshot release

---

.github/workflows/maven-publish.yaml

Correctly set PATH to run xq

---

.github/workflows/maven-publish.yaml

Cat the poms for debugging

---

.github/workflows/maven-publish.yaml
backend-base/pom.xml
javascript/pom.xml
pom.xml

Set everything back to normal for che-incubator

---

.github/workflows/publish.yaml

Don't pull

---

.github/workflows/maven.yml
.github/workflows/nodejs-ci.yaml

Make the CI jobs run on PRs to master too

---

README.md
devfile.yaml

Add devfile and Workspace button

---

backend-base/src/main/java/org/eclipse/che/incubator/workspace/telemetry/base/BaseConfiguration.java
backend-base/src/test/java/org/eclipse/che/incubator/workspace/telemetry/TelemetryResourceTest.java
backend-base/src/test/java/org/eclipse/che/incubator/workspace/telemetry/base/AbstractAnalyticsManagerTest.java

part of https://github.com/eclipse/che/issues/18107

Remove che.api configuration property, and use the workspace builtin che.api.internal

---

javascript/src/typescript/README.md

Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
Should add README to https://www.npmjs.com/package/@eclipse-che/workspace-telemetry-client

Adding README.md to the @eclipse-che/workspace-telemetry-client package

---

backend-base/src/main/java/org/eclipse/che/incubator/workspace/telemetry/base/AbstractAnalyticsManager.java

Log a nicer message when the created date, update date, or stop date field from the Workspace API fails to parse 
Signed-off-by: Tom George <tgeorge@redhat.com>

Log a nicer message when dates fail to parse

---

backend-base/src/main/java/org/eclipse/che/incubator/workspace/telemetry/anonymizer/SHA1HashGenerator.java
backend-base/src/main/java/org/eclipse/che/incubator/workspace/telemetry/base/AbstractAnalyticsManager.java
backend-base/src/test/java/org/eclipse/che/incubator/workspace/telemetry/anonymizer/SHA1HashGeneratorTest.java

Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

Fixing the SHA1HashGenerator usage

---

backend-base/README.md
backend-base/src/main/java/org/eclipse/che/incubator/workspace/telemetry/base/AbstractAnalyticsManager.java
backend-base/src/test/java/org/eclipse/che/incubator/workspace/telemetry/base/AbstractAnalyticsManagerTest.java

Quick PR to do some cleaning and fix https://github.com/che-incubator/che-workspace-telemetry-client/issues/96
Signed-off-by: David Kwon <dakwon@redhat.com>

Remove unnecessary local variables and method

---

.github/workflows/maven-ci.yaml
.github/workflows/publish.yaml

Changes for https://github.com/eclipse/che/issues/21763

chore: Update ubuntu to 22.04 and actions to node 16 versions
